name: Build Tweak
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential perl git libssl-dev xz-utils

      - name: Setup Everything
        run: |
          # On utilise le script qui a marché au build précédent
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          
          # On définit les variables pour que GitHub les reconnaisse
          echo "THEOS=/home/runner/theos" >> $GITHUB_ENV
          echo "/home/runner/theos/bin" >> $GITHUB_PATH

      - name: Build Package
        run: |
          # On exporte manuellement THEOS juste pour être sûr
          export THEOS=/home/runner/theos
          # On lance la compilation directement
          # Le script installe par défaut le SDK iPhoneOS16.5.sdk ou similaire
          make package FINALPACKAGE=1
        env:
          THEOS: /home/runner/theos

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: JoyBoyModMenu-Package
          path: ./*.deb
