name: Build Tweak
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential perl git libssl-dev xz-utils

      - name: Setup Theos & Toolchain
        run: |
          # Installation automatique de Theos et de la Toolchain
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          echo "THEOS=/home/runner/theos" >> $GITHUB_ENV
          echo "/home/runner/theos/bin" >> $GITHUB_PATH

      - name: Setup SDK (Direct Clone)
        run: |
          # On clone le SDK (cette partie-là marchait bien chez toi !)
          mkdir -p /home/runner/theos/sdks
          git clone --depth 1 https://github.com/theos/sdks.git /home/runner/theos/sdks

      - name: Build Package
        run: |
          export THEOS=/home/runner/theos
          # On lance la compilation
          make package FINALPACKAGE=1 SDKPATH=/home/runner/theos/sdks/iPhoneOS14.5.sdk
        env:
          THEOS: /home/runner/theos

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: JoyBoyModMenu-Package
          path: ./*.deb
